### ISSUE TITLE
Few alternative methods

### ISSUE THREAD

**Issue by prnvpwr2612** [Mister2005/Infomatrix-Data-Science-Tasks#1]
Hi @Mister2005 ,

Good job!
Glad to see all the tasks being completed. However there are few things which you could have done better. Could have leveraged the in-built functions in a better way.

1. Like in Q2) a), you could have used **mode function** to find the most frequent value.
2. And similarly in Q3) i), you could have used **df.describe()** to get all necessary details, if few weren't present you could have then calculated them singularly.

But good job good to see the enthusiasm.
Keep it up!

**Comment by Mister2005** [comment]
Ok thanks @prnvpwr2612 for reviewing the task next time I'll try to use efficient methods.
